from .base import BaseTool, ToolDefinition, ToolParameter, ToolResult
from .registry import ToolRegistry
from .drawing import (
    DrawCircleTool, DrawRectTool, DrawLineTool, DrawTextTool, DrawEllipseTool,
    DrawPolygonTool, DrawPolylineTool, DrawPathTool,
    DrawVectorCompositionTool,
    DrawPerspectiveVehicleTool,
    DrawConcentricCirclesTool,
)
from .editing import (
    DeleteObjectTool,
    MoveObjectTool,
    ChangeColorTool,
    ResizeObjectTool,
    RotateObjectTool,
    FlipObjectTool,
    SkewObjectTool,
    ArrangeObjectTool,
    AlignObjectTool,
    DistributeObjectsTool,
    DuplicateObjectTool,
    GroupObjectsTool,
    UngroupObjectsTool,
    ChangeOpacityTool,
    ChangeStrokeTool,
    SelectObjectTool,
    SelectByRegionTool,
    SelectByLassoTool,
    SelectSimilarTool,
    ChangeFillTool,
    ApplyGradientFillTool,
    CopyObjectStyleTool,
    CropObjectTool,
    ApplyClipMaskTool,
    ChangeBlendModeTool,
    ApplyImageFilterTool,
)
from .history import UndoTool, RedoTool, ClearCanvasTool
from .assets import (
    SearchVectorAssetTool,
    ImportVectorAssetTool,
    ReplaceVectorAssetTool,
    ListAssetCandidatesTool,
)
from .execution import (
    ReadFileTool, WriteFileTool, ListDirTool,
    BashTool, SearchTextTool, PatchFileTool,
)

ALL_TOOLS = [
    DrawCircleTool,
    DrawRectTool,
    DrawLineTool,
    DrawTextTool,
    DrawEllipseTool,
    DrawPolygonTool,
    DrawPolylineTool,
    DrawPathTool,
    DrawConcentricCirclesTool,
    DrawVectorCompositionTool,
    DrawPerspectiveVehicleTool,
    DeleteObjectTool,
    MoveObjectTool,
    ChangeColorTool,
    ResizeObjectTool,
    RotateObjectTool,
    FlipObjectTool,
    SkewObjectTool,
    ArrangeObjectTool,
    AlignObjectTool,
    DistributeObjectsTool,
    DuplicateObjectTool,
    GroupObjectsTool,
    UngroupObjectsTool,
    ChangeOpacityTool,
    ChangeStrokeTool,
    SelectObjectTool,
    SelectByRegionTool,
    SelectByLassoTool,
    SelectSimilarTool,
    ChangeFillTool,
    ApplyGradientFillTool,
    CopyObjectStyleTool,
    CropObjectTool,
    ApplyClipMaskTool,
    ChangeBlendModeTool,
    ApplyImageFilterTool,
    UndoTool,
    RedoTool,
    ClearCanvasTool,
    ReadFileTool,
    WriteFileTool,
    ListDirTool,
    BashTool,
    SearchTextTool,
    PatchFileTool,
    SearchVectorAssetTool,
    ImportVectorAssetTool,
    ReplaceVectorAssetTool,
    ListAssetCandidatesTool,
]

__all__ = [
    "BaseTool", "ToolDefinition", "ToolParameter", "ToolResult",
    "ToolRegistry",
    "DrawCircleTool", "DrawRectTool", "DrawLineTool", "DrawTextTool", "DrawEllipseTool",
    "DrawPolygonTool", "DrawPolylineTool", "DrawPathTool",
    "DrawConcentricCirclesTool",
    "DrawVectorCompositionTool",
    "DrawPerspectiveVehicleTool",
    "DeleteObjectTool", "MoveObjectTool", "ChangeColorTool", "ResizeObjectTool",
    "RotateObjectTool", "FlipObjectTool", "SkewObjectTool",
    "ArrangeObjectTool", "AlignObjectTool", "DistributeObjectsTool",
    "DuplicateObjectTool", "GroupObjectsTool", "UngroupObjectsTool",
    "ChangeOpacityTool", "ChangeStrokeTool",
    "SelectObjectTool", "SelectByRegionTool", "SelectByLassoTool", "SelectSimilarTool",
    "ChangeFillTool", "ApplyGradientFillTool", "CopyObjectStyleTool",
    "CropObjectTool", "ApplyClipMaskTool",
    "ChangeBlendModeTool", "ApplyImageFilterTool",
    "UndoTool", "RedoTool", "ClearCanvasTool",
    "ReadFileTool", "WriteFileTool", "ListDirTool",
    "BashTool", "SearchTextTool", "PatchFileTool",
    "SearchVectorAssetTool", "ImportVectorAssetTool",
    "ReplaceVectorAssetTool", "ListAssetCandidatesTool",
    "ALL_TOOLS",
]
